# Generated by Django 2.1.7 on 2019-06-05 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_like', models.ManyToManyField(null=True, related_name='add_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
