# Generated by Django 2.1.7 on 2019-06-05 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_addlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlike',
            name='add_like',
            field=models.ManyToManyField(blank=True, related_name='add_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
