# Generated by Django 2.1.7 on 2019-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190605_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlike',
            name='add_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
