# Generated by Django 2.1.7 on 2019-05-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_flagship'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPhoneComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='SmartPhoneComp')),
                ('name2', models.CharField(max_length=50)),
                ('image2', models.ImageField(upload_to='SmartPhoneComp')),
            ],
        ),
    ]
