# Generated by Django 2.1.7 on 2019-06-15 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_auto_20190615_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='posting_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
