# Generated by Django 2.1.7 on 2019-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodcutSearch', '0004_auto_20190218_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='smallContent',
            field=models.TextField(default='hello there'),
            preserve_default=False,
        ),
    ]
