# Generated by Django 2.1.7 on 2019-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodcutSearch', '0006_phonetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetype',
            name='page',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
