# Generated by Django 2.1.7 on 2019-05-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodcutSearch', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(default=1, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
