# Generated by Django 2.1.7 on 2019-05-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodcutSearch', '0011_auto_20190526_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(auto_created=True, blank=True, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
