# Generated by Django 2.1.7 on 2019-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodcutSearch', '0017_auto_20190526_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(auto_created=True, default=1, max_length=10, primary_key=True, serialize=False),
        ),
    ]
