# Generated by Django 2.1.7 on 2019-05-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodcutSearch', '0018_auto_20190526_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(auto_created=True, default=True, max_length=5, primary_key=True, serialize=False),
        ),
    ]
