# Generated by Django 2.1.7 on 2019-05-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodcutSearch', '0019_auto_20190526_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='prodcutSearch.Comment'),
            preserve_default=False,
        ),
    ]
